name: Backend Continuous Deployment

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: Build Backend Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and Push Docker Image
        working-directory: starter/backend
        run: |
          docker build -t ${{ secrets.ECR_BACKEND_REPO }}:${{ github.sha }} .
          docker push ${{ secrets.ECR_BACKEND_REPO }}:${{ github.sha }}

  deploy:
    name: Deploy Backend to Kubernetes
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Configure kubectl for EKS
        run: aws eks update-kubeconfig --region ${{ secrets.AWS_REGION }} --name movie-picture-cluster

      - name: Install Kustomize
        run: |
          curl -s https://api.github.com/repos/kubernetes-sigs/kustomize/releases/latest \
          | grep browser_download_url \
          | grep linux_amd64 \
          | cut -d '"' -f 4 \
          | wget -qi -
          tar xzf kustomize_*_linux_amd64.tar.gz
          sudo mv kustomize /usr/local/bin

      - name: Deploy to Kubernetes
        working-directory: starter/backend/k8s
        run: |
          kustomize edit set image backend=${{ secrets.ECR_BACKEND_REPO }}:${{ github.sha }}
          kustomize build | kubectl apply -f -
