name: Backend Continuous Integration

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  lint:
    name: Lint Backend Code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Python 3.10
        run: sudo apt-get install python3.10 python3.10-venv python3.10-dev

      - name: Install pipenv
        run: pip install pipenv

      - name: Install Dependencies
        run: pipenv install --dev
        working-directory: starter/backend

      - name: Check installed packages
        run: pipenv run pip show flake8
        working-directory: starter/backend

      - name: Run Linter
        run: pipenv run lint
        working-directory: starter/backend
