name: Backend Continuous Integration

on:
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Checkout source code
      - name: Checkout code
        uses: actions/checkout@v3

      # Build Docker image (chuyển đúng thư mục)
      - name: Build Docker image
        run: docker build -t backend:latest ./starter/backend

      # Run tests inside Docker container
      - name: Run tests inside Docker container
        run: docker run --rm backend:latest pytest /app/test_app.py
