name: Backend Continuous Integration

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  lint:
    name: Lint Backend Code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Python 3.10
        run: sudo apt-get install python3.10 python3.10-venv python3.10-dev

      - name: Install pipenv
        run: |
         cd starter
         cd backend
         pip install pipenv
        working-directory: starter/backend

      - name: Install Dependencies
        run: |
         cd starter
         cd backend
         pipenv install --dev
        working-directory: starter/backend

      - name: Run Linter
        run: |
         cd starter
         cd backend
         pipenv run flake8 .
        working-directory: starter/backend

  test:
    name: Test Backend Code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install pipenv
        run: pip install pipenv

      - name: Install Dependencies
        run: pipenv install
        working-directory: starter/backend

      - name: Run Tests
        run: pipenv run test
        working-directory: starter/backend

  build:
    name: Build Backend Docker Image
    needs:
      - lint
      - test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1  # Thay đổi nếu cần, tùy thuộc vào vùng của bạn

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and Push Docker Image
        run: |
          docker build -t ${{ secrets.ECR_BACKEND_REPO }}:${{ github.sha }} .
          docker push ${{ secrets.ECR_BACKEND_REPO }}:${{ github.sha }}
        working-directory: starter/backend
