name: Backend Continuous Integration

on:
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Checkout source code
      - name: Checkout code
        uses: actions/checkout@v3

      # Move to the backend directory
      - name: Change directory to backend
        working-directory: ./starter/backend
        run: pwd

      # Build Docker image
      - name: Build Docker image
        working-directory: ./starter/backend
        run: docker build -t backend:latest .

      # Run tests
      - name: Run tests inside Docker container
        run: |
          docker run --rm backend:latest pytest /app/test_app.py
