name: Backend Continuous Integration

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  lint:
    name: Lint Backend Code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Python 3.10
        run: sudo apt-get install python3.10 python3.10-venv python3.10-dev

      - name: Install Dependencies
        run: |
          python3 -m venv venv
          source venv/bin/activate
          pip install -r starter/backend/Pipfile
          pip install flake8
        working-directory: starter/backend

      - name: Run Linter
        run: |
          source venv/bin/activate
          flake8 .
        working-directory: starter/backend

