name: Frontend Continuous Deployment
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: npm install
        working-directory: ./starter/frontend  # Thêm dòng này để chỉ định đúng thư mục

      - name: Run Tests
        run: npm run test
        working-directory: ./starter/frontend  # Thêm dòng này để chỉ định đúng thư mục

      - name: Build Docker image
        run: docker build -t frontend:latest .
        working-directory: ./starter/frontend  # Thêm dòng này để chỉ định đúng thư mục
