name: Frontend Continuous Integration
on:
  pull_request:
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: npm install
        working-directory: ./starter/frontend  # Thêm dòng này để chỉ định đúng thư mục

      - name: Run Linter
        run: npm run lint
        working-directory: ./starter/frontend  # Thêm dòng này để chỉ định đúng thư mục

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: npm install
        working-directory: ./starter/frontend  # Thêm dòng này để chỉ định đúng thư mục

      - name: Run Tests
        run: npm run test
        working-directory: ./starter/frontend  # Thêm dòng này để chỉ định đúng thư mục
